name: Build and Push TypeScript Node.js App

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/typescript-nodejs-server

jobs:
  build-and-push:
    runs-on: depot-ubuntu-24.04-4
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest

      - name: Setup Depot CLI
        uses: depot/setup-action@v1

      - name: Build and push Docker image
        uses: depot/build-push-action@v1
        with:
          project: 9rvjk64s1l
          context: ./typescript-nodejs
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      # - name: Trigger workflow to replace image
      #   env:
      #     GH_TOKEN: ${{ secrets.WORKFLOW_ACTIONS_TOKEN }}
      #   run: |
      #     gh workflow run modify-image.yaml --repo LearnWithTwoHeads/argocd-kustomize-infra --field project=typescript-app --field version=sha-${GITHUB_SHA::7} --field environment=dev
